language: objective-c
before_install:
  - sudo chown -R travis ~/Library/RubyMotion
  - mkdir -p ~/Library/RubyMotion/build
  - sudo motion update
  - bundle install
  - bundle exec rake pod:install | grep \.podspec -v | grep -e "^$" -v
